### ISSUE TITLE
Timestamp/Datetime default value current_timestamp() bug.

### ISSUE THREAD

**Issue by Bishawjit-Mondol** [robinNcode/db_craft#1]
'created_at' should get the timestamp value automatically, but it didn't.

**Comment by robinNcode** [comment]
@Bishawjit-Mondol Thanks for your feedback. In shaa Allah this issue will be resolved as soon as possible.

**Comment by robinNcode** [comment]
@Bishawjit-Mondol the issue has been resolved with version 1.1.0, Now you can update the package and save your time.
