### ISSUE TITLE
MigrationGenerator file

### ISSUE THREAD

**Issue by pk-kissdevs** [robinNcode/db_craft#2]
Robinncode\DbCraft\Libraries throws an error on line 269 due to double quotes. It should change to below:
            `$keyArray[] = '\n\t\t\$this->forge->addForeignKey(\'$key->column_name\',\'$key->foreign_table_name\',\'$key->foreign_column_name\',\CASCADE\',\'CASCADE\');';`

FileHandler also throws error if app name is not 'app. Line 76 should change to below:
`        $targetDir = APPPATH . '/Database/Migrations/';`

**Comment by clsmedia** [comment]
👍 
`$keyArray[] = PHP_EOL . chr(9) . chr(9) . '$this->forge->addForeignKey(\'$key->column_name\',\'$key->foreign_table_name\',\'$key->foreign_column_name\',\'CASCADE\',\'CASCADE\');';`
