### ISSUE TITLE
Bug: Database names with dash not working

### ISSUE THREAD

**Issue by hirsm** [robinNcode/db_craft#6]
Hi and thanks for your great tool.

I am facing a problem regarding table names with dashes, because they lead to exceptions. It is however working when adding backticks just like in ``php spark get:migration `my-table` `` but you have to work-up the migration files by hand afterwards to remove the backticks in places where they do not belong.

**Comment by robinNcode** [comment]
**@hirsm** Thanks for your kind feedback.
It is not good practice to write table names with dashes in MySql. Check out this small conversation with Chat-GPT [is it a good practice to write MySQL table name with dash like "student-info"?](https://chatgpt.com/share/31a0d6b1-5c15-4d42-98ec-4d4ea8886aa0)
Still, if you want me to resolve this mentioned exception, I will do it in the next patch.

**Comment by hirsm** [comment]
@robinNcode you are absolutely right, it really is bad practise to write table names with dashes (and I will not do it again^^). However, I think I will not be the only doing it so I would kindly appreciate a fix if you have the time for it.

**Comment by robinNcode** [comment]
Sorry to say. We are not fixing this issue. Will see it later in future.
